### ISSUE TITLE
Core Importer not Importing records

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1062]
**Describe the Bug**
A user made a new record in CORE last week and Core has shown 0/0 in regards to uploads since before this. and has continued to show this same result in NRPTI.

**Expected Behaviour**
when a new Core record is created, it would be picked up by NRPTI

**Actual Behaviour**
the new core record and possibly others have not been picked up by NRPTI yet

**Implications**
NRCED cannot display the most up to date information as designed without this functionality working. 

** Steps To Reproduce**
Steps to reproduce the behaviour:
we would need a user to create another core record to double check it. possibly in TEST

**Comment by Christopher-walsh22** [comment]
This issue has been occuring since May 4th 2023. Since this date there has been two documents that cause an error in the importer. The offending files are: 
![image.png](https://images.zenhubusercontent.com/629513fec61736deae137911/24cc5213-eee9-45c5-a2a8-0a5dc80aad8f)
![image.png](https://images.zenhubusercontent.com/629513fec61736deae137911/36e65331-81a9-4a35-aeac-7f79c1950ef3)

Will reach out to the mds team to find out if there is anything different about these two records in particular.
