### ISSUE TITLE
[BUG] AMP records for individuals uploaded to NRCED are redacted despite provided age

### ISSUE THREAD

**Issue by malafry** [bcgov/NRPTI#1239]
**Describe the Bug**
When a user uploads an administrative penalty record issued under the Environmental Management Act (EMA) via NRPTI, and that record is issued to an individual (older than 18 years old/not a minor) with attached documents, the record will upload to NRPTI/NRCED. On NRPTI, it shows appropriately. On NRCED, it shows inappropriately: (1) "Issued To" shows as "Unpublished", and (2) "Documents" shows as "This record does not have any documents."

**Expected Behaviour**
When a user uploads an administrative penalty record for an individual (that is not a minor), their name should be published and documents should be viewable.

**Actual Behaviour**
When a user uploads an administrative penalty record for an individual (that is not a minor), their name is unpublished and no documents are viewable. The selected age of the individual does not matter.

**Implications**
Users of NRCED do not have full access to enforcement records, which they should have.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Add record' on NRPTI.
2. Add an administrative penalty record under Environmental Management Act (section 115) with any type of data.
3. Add an age (default is 1900-12-31, but any age will do where it's greater than 18).
4. Add a test document.
5. Save and publish record to NRCED.
6. Record will show "Issued To" as "Unpublished" and will not include documents.

**Comment by Keegnan** [comment]
@acatchpole @sggerard  Please estimate this when you get a chance.

**Comment by acatchpole** [comment]
This issue is not related to the act associated with it. Test records using a different act and no act had the same bug behaviour.

**Comment by acatchpole** [comment]
In the redaction process, in the business-logic-manager, there was a check to see if the writing agency was one of the agencies that had permission to publish individual names. if it was not one of those agencies, names and docs would be removed. BUT it was comparing the actual agency names to the agencyCodes. This code was refactored to make sure that codes were compared to code. Alas, this has not fixed the issue, likely due to the fact that one of the end methods had to be converted to async and now a bunch of parent functions have not been completely refactored to handle promises.

**Comment by acatchpole** [comment]
bandaid fix and migration to address improperly redacted AMPs deployed to prod
