### ISSUE TITLE
redirect link on BCMI that directs to the corresponding search on NRCED

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1262]
**As a** *member of the public* **I want** *a link to all relevant records of a mine on BCMI* **So That** *I can see their history of compliance*

**Additional Context**
- Linking to NRCED will help show all the inspections
- BCMI only tracks major mines and mines of note
- Only need the mines within BCMI
- The link will show a pre-searched of BCMI
- There is not a perfect match of mine names - some use abbreviation 

**Acceptance Criteria**
- on each Mine page on BCMI, I want a link on BCMI that redirects to the corresponding search on NRCED

**Comment by Keegnan** [comment]
Reaching out to Colin might help with coming up with a better solution with some of the names and creating a proper mapping table with the mine names.

**Comment by Keegnan** [comment]
Completing this as the first slice - Adding a link to all BCMI mines to existing records in NRCED.

**Comment by sggerard** [comment]
Should be able to use company name to match. Need to make changes to NCRED first to support searching NRPTI by companyName. 

e.g. including &or[issuedTo.companyName]=KGHM%20Ajax%20Mining%20Inc)

**Comment by sggerard** [comment]
Using company name doesn't work as one company can have multiple mines, additionally there are other issues such as case and and vs &.

The projectName field on Inspections in NRPTI seems like a good candidate, it appears to store the mine name. However the NRIS-EPD doesn't currently set that field. NRIS-EMLI does based on the locationName field but it varies. (e.g Silvertip instead of Silvertip mine. However the locationID field matches the mine_no of the CORE mine but this is not a field that we are currently capturing.

It appears the best approach for correctly joining NRIS to CORE is to:
1. Store mine_no (e.g 0100525) against BCMI Mine records as part of the CORE importer.
2. Update the NRIS-EPD and NRIS-EMLI importers to do a lookup of mine name based on location.locationID = mine_no and store the mine name in the projectName field.
3. Allow searching of projectName in NCRED

**Comment by sggerard** [comment]
Changes deployed to test environments for both BCMI & NRPTI. A link to NRCED shows on the Compliance Oversight tab of each mine in BCMI. 

![Image](https://github.com/user-attachments/assets/0cf4b5b9-d122-493f-970e-7acce1291858)

**Comment by Keegnan** [comment]
@sggerard Hoping you can give us an update on the status of this ticket. Are we still waiting for SO approval?

**Comment by sggerard** [comment]
This work did not get SO approval, due to the records on NRCED not matching the records on BCMI for a number of valid reasons. This work has been moved behind a feature flag on BCMI and will not be published until other work such as #1274 has been completed. I think this ticket can be closed and just needs to be noted as part of the future work.
