### ISSUE TITLE
Auto-populate Regulations Field

### ISSUE THREAD

**Issue by LolandaE** [bcgov/NRPTI#982]
**As a** *(User Type/Persona)* **I want** *to be able to have the description field auto-populate when I type in Fish and Seafood Licensing Regulation* **So That** *I don't have to remember all the legislation*

**Additional Context**
- Functionality exists. This specific use case doesn't.
- Jake to confirm this is NRPTI (not NRCED).
- Program a new auto-populated Description field for a new Legislation: when a new entry is put in NRPTI, they have the option to have a legislation added like this (picture below)|
- If the legislation is already “pre-coded” then the description field will be auto-populated. But if the legislation is new to NRPTI, then we need to add the new description. The new legislation is "Fish and Seafood Licensing Regulation, section 21(1)(a)".  The offence should read: "Operate as fish receiver without licence."
- Leave Act and Paragraph off the ticket

![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/59c3064d-5cb6-412d-8255-41da89eb7f7b)

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by RFK250** [comment]
@jakemorr This user story doesn't make sense to me. The Legislation fields function well, and the description does auto-populate when a known combination of act/reg/sec/sub/para is entered. The only potential improvement that might be here is: if FSLR 21(1)(a) is the only FSLR 21 legislation in the system (i.e. there is no 21(1)(b), 21 (2), etc) ) then the description could be auto-populated... But just because there's no FSLR 21(2) in the system, it does not follow that a user may want to enter an FSLR 21(2) record one day.

I suggest putting this ticket in the "won't do" pile, as the feature is already functional and users shouldn't have to remember all the legislation in the first place - in theory, they are transcribing data from another source (e.g. a physical violation ticket) and thus should have all the legislation right in front of them.
