### ISSUE TITLE
Enable NRIS-EMLI importer

### ISSUE THREAD

**Issue by norrisng-bc** [bcgov/NRPTI#986]
**As a** *Service Owner* **I want** *to enable scheduled importing of data from NRIS-EMLI* **So That** *I can view that data in NRCED, NRPTI, and BCMI*.

**Additional Context**
- NRIS-EMLI is an external database/API. NRPTI will pull data from here via a cronjob.
- This functionality has already been implemented by the previous team (see PR #842 / [NRPT-707 in BCMI Jira](https://bcmines.atlassian.net/browse/NRPT-707)), but wasn't enabled as NRIS-EMLI wasn't ready yet.
- In #981, research was done and tweaks were made to prepare for this enabling.
- Now, all that needs to be done to enable the importer, is to toggle 2 environment variables from `false` to `true` (see PR #985 for more info).
- this is working in Test-NRCED, however we need to confirm it is updating on the Test-BCMI side (check with Jack)
**the uploader between the test NRIS-EMLI and the test-BCMI is not active. Is it possible to turn that on so we can see if the records are displaying properly before going into production?**
- if EMLI side isnt publishing it could have to do with "Collections" ask Service Owner

**Acceptance Criteria**
- [ ] Given that NRIS-EMLI is ready, when the EMLI importer cronjob runs, data from NRIS-EMLI should be visible in NRCED, NRPTI, and BCMI.

**Comment by jakemorr** [comment]
we need to know if BCMI is making a cal to NRPTI for this data? how is it supposed to get to their web app otherwise?

**Comment by RFK250** [comment]
@jakemorr Is there any reason to not split this ticket into two stories, i.e. one for publishing to NRCED and one for publishing to BCMI, so that BCMI doesn't block publishing to NRCED? The only issue I could think of would be if the BCMI SO had a valid program reason for not wanting to see data published to NRCED without also being published to BCMI. Otherwise, there's no harm in splitting it, releasing the NRCED story and then tackling the BCMI story later.
