### ISSUE TITLE
Identify Document Location When Uploaded via NRIS-EPD Uploader - NRPTI

### ISSUE THREAD

**Issue by LolandaE** [bcgov/NRPTI#999]
**As a** Service Owner/NRPTI User **I want to** know where a document is stored when it is uploaded as part of the NRIS-EPD uploader **so that** we still have access to the document if NRIS fails.

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by RFK250** [comment]
@jakemorr Documents are stored in S3 buckets - or at least they were at launch.

This user story doesn't make sense to me, unless it is supposed to read "so that we still have access to the document if **the NRIS-EPD importer** fails" - then there is potentially a use case... But even then I'm not sure there is. And if it really is about NRIS failing, well... Users can access documents via the regular NRCED UI.
